-- Brainrot Characters (150+ entries)
-- Common (tier 1, weight ~5-10 each) ~70 entries
insert into public.brainrot_characters (name,name_ar,image_url,rarity,rarity_ar,tier,weight,is_real,description) values
('Tung Sahur','تونغ ساهور','https://i.imgur.com/tung1.jpg','common','عادي',1,10,true,'مساء الفجر'),
('Brr Patapim','بر باتابيم','https://i.imgur.com/brr1.jpg','common','عادي',1,10,true,'صوت الجليد'),
('Bombardiro Crocodilo','قناص التمساح','https://i.imgur.com/bomb1.jpg','common','عادي',1,10,true,'قناص المستنقعات'),
('Glorb','غلورب','https://i.imgur.com/glorb1.jpg','common','عادي',1,10,true,'وحش الأنهار'),
('Trippi Troppi','تريبي تروبي','https://i.imgur.com/trippi1.jpg','common','عادي',1,10,true,'طائر السعادة'),
('Drago Pazzo','التنين المجنون','https://i.imgur.com/drago1.jpg','common','عادي',1,10,true,'نيران لا تطفأ'),
('Squalo Elettrico','القرش الكهربائي','https://i.imgur.com/squalo1.jpg','common','عادي',1,10,true,'صدمة المحيط'),
('Ninja Fortunato','النينجا المحظوظ','https://i.imgur.com/ninja1.jpg','common','عادي',1,10,true,'ظل الليل'),
('Pasta Volante','الباستا الطائرة','https://i.imgur.com/pasta1.jpg','common','عادي',1,10,true,'رمي سريع'),
('Caffe Furioso','القهوة الغاضبة','https://i.imgur.com/caffe1.jpg','common','عادي',1,10,true,'لا ينام'),
('Pizza Rotante','البيتزا الدوارة','https://i.imgur.com/pizza1.jpg','common','عادي',1,9,true,'تدور بلا توقف'),
('Banana Atomica','الموزة الذرية','https://i.imgur.com/banana1.jpg','common','عادي',1,9,true,'انفجار صفراء'),
('Gatto Laser','القط الليزري','https://i.imgur.com/gatto1.jpg','common','عادي',1,9,true,'عين حمراء'),
('Cane Vortex','الكلب الدوار','https://i.imgur.com/cane1.jpg','common','عادي',1,9,true,'يلتهم الرياح'),
('Rana Glitch','الضفدع المختل','https://i.imgur.com/rana1.jpg','common','عادي',1,9,true,'بكسل مكسور'),
('Serpente Pixel','الثعبان البكسلي','https://i.imgur.com/serp1.jpg','common','عادي',1,9,true,'8-bit قاتل'),
('Uccello Disco','طائر الديسكو','https://i.imgur.com/uccel1.jpg','common','عادي',1,9,true,'كرات المرآة'),
('Topo Sonic','الفأر الصوتي','https://i.imgur.com/topo1.jpg','common','عادي',1,9,true,'أسرع من الضوء'),
('Maiale Cosmico','الخنزير الكوني','https://i.imgur.com/maial1.jpg','common','عادي',1,9,true,'نجوم في عينيه'),
('Mucca Vapore','البقرة البخارية','https://i.imgur.com/mucca1.jpg','common','عادي',1,9,true,'سحابة حليب'),
('Lupo Neve','ذئب الثلج','https://i.imgur.com/lupo1.jpg','common','عادي',1,9,true,'برد أبدي'),
('Volpe Fuoco','ثعلب النار','https://i.imgur.com/volpe1.jpg','common','عادي',1,9,true,'ذيل مشتعل'),
('Orso Ghiaccio','دب الجليد','https://i.imgur.com/orso1.jpg','common','عادي',1,9,true,'كوكب متجمد'),
('Scimmia Pixel','قرد البكسل','https://i.imgur.com/scimm1.jpg','common','عادي',1,9,true,'تسلق الشاشة'),
('Tartaruga Veloce','السلحفاة السريعة','https://i.imgur.com/tarta1.jpg','common','عادي',1,9,true,'سرعة خارقة'),
('Coniglio Elettrico','الأرنب الكهربائي','https://i.imgur.com/conig1.jpg','common','عادي',1,9,true,'أذن برق'),
('Giraffa Laser','الزرافة الليزرية','https://i.imgur.com/giraf1.jpg','common','عادي',1,9,true,'رقبة ضوء'),
('Elefante Nebula','الفيل السديمي','https://i.imgur.com/elefa1.jpg','common','عادي',1,9,true,'كوكب على ظهره'),
('Pinguino Vulcano','البطريق البركاني','https://i.imgur.com/pingu1.jpg','common','عادي',1,9,true,'حمم متجمدة'),
('Leone Pixel','الأسد البكسلي','https://i.imgur.com/leone1.jpg','common','عادي',1,9,true,'زئير 8-bit'),
('Zebra Glitch','الحمار الوحشي المختل','https://i.imgur.com/zebra1.jpg','common','عادي',1,9,true,'خطوط مكسورة'),
('Koala Cosmico','الكوالا الكوني','https://i.imgur.com/koala1.jpg','common','عادي',1,9,true,'أحلام النجوم'),
('Panda Vapore','البندا البخاري','https://i.imgur.com/panda1.jpg','common','عادي',1,9,true,'بامبو سحري'),
('Canguro Fuoco','كنغر النار','https://i.imgur.com/cangu1.jpg','common','عادي',1,9,true,'قفزات لهب'),
('Lama Laser','اللاما الليزرية','https://i.imgur.com/lamal1.jpg','common','عادي',1,9,true,'بصاق ضوء'),
('Foca Disco','فقمة الديسكو','https://i.imgur.com/foca1.jpg','common','عادي',1,9,true,'رقصة الجليد'),
('Struzzo Atomico','النعامة الذرية','https://i.imgur.com/struz1.jpg','common','عادي',1,9,true,'رأس تحت الرمال'),
('Rinoceronte Pixel','وحيد القرن البكسلي','https://i.imgur.com/rino1.jpg','common','عادي',1,9,true,'قرن رقمي'),
('Ippopotamo Glitch','فرس النهر المختل','https://i.imgur.com/ippop1.jpg','common','عادي',1,9,true,'ماء مكسور'),
('Coccodrillo Sonic','تمساح سونيك','https://i.imgur.com/cocco1.jpg','common','عادي',1,9,true,'أسنان صوتية'),
('Pollo Cosmico','الدجاجة الكونية','https://i.imgur.com/pollo1.jpg','common','عادي',1,9,true,'بيض نجوم'),
('Pecora Vapore','الخروف البخاري','https://i.imgur.com/pecor1.jpg','common','عادي',1,9,true,'صوف سحاب'),
('Capra Fuoco','الماعز الناري','https://i.imgur.com/capra1.jpg','common','عادي',1,9,true,'قرون لهب'),
('Asino Laser','الحمار الليزري','https://i.imgur.com/asino1.jpg','common','عادي',1,9,true,'صهيل ضوء'),
('Cavallo Atomico','الحصان الذري','https://i.imgur.com/caval1.jpg','common','عادي',1,9,true,'حوافر انفجار'),
('Toro Pixel','الثور البكسلي','https://i.imgur.com/toro1.jpg','common','عادي',1,9,true,'قرون 16-bit'),
('Gallo Glitch','الديك المختل','https://i.imgur.com/gallo1.jpg','common','عادي',1,9,true,'صيحة مكسورة'),
('Anatra Disco','بطة الديسكو','https://i.imgur.com/anatr1.jpg','common','عادي',1,9,true,'رقصة الماء'),
('Pavone Cosmico','الطاووس الكوني','https://i.imgur.com/pavon1.jpg','common','عادي',1,9,true,'ريش نجوم'),
('Gufo Vapore','البومة البخارية','https://i.imgur.com/gufo1.jpg','common','عادي',1,8,true,'حكمة الضباب'),
('Corvo Fuoco','غراب النار','https://i.imgur.com/corvo1.jpg','common','عادي',1,8,true,'ريش مشتعل'),
('Passero Laser','العصفور الليزري','https://i.imgur.com/passe1.jpg','common','عادي',1,8,true,'غردة ضوء'),
('Aquilone Pixel','الطائرة البكسلية','https://i.imgur.com/aquil1.jpg','common','عادي',1,8,true,'تحليق رقمي'),
('Pesce Glitch','السمكة المختلة','https://i.imgur.com/pesch1.jpg','common','عادي',1,8,true,'زعنفة مكسورة'),
('Medusa Disco','قنديل الديسكو','https://i.imgur.com/medus1.jpg','common','عادي',1,8,true,'لمعان المحيط'),
('Stella Atomica','النجمة الذرية','https://i.imgur.com/stell1.jpg','common','عادي',1,8,true,'انفجار ساطع'),
('Luna Vapore','القمر البخاري','https://i.imgur.com/luna1.jpg','common','عادي',1,8,true,'ضوء خافت'),
('Sole Pixel','الشمس البكسلية','https://i.imgur.com/sole1.jpg','common','عادي',1,8,true,'حرارة 8-bit'),
('Pianeta Glitch','الكوكب المختل','https://i.imgur.com/piane1.jpg','common','عادي',1,8,true,'مدار مكسور'),
('Meteora Fuoco','النيزك الناري','https://i.imgur.com/meteo1.jpg','common','عادي',1,8,true,'سقوط ساطع'),
('Cometa Laser','المذنب الليزري','https://i.imgur.com/comet1.jpg','common','عادي',1,8,true,'ذيل ضوء'),
('Galassia Disco','مجرة الديسكو','https://i.imgur.com/galas1.jpg','common','عادي',1,8,true,'نجوم تراقص'),
('Nebulosa Atomica','السديمة الذرية','https://i.imgur.com/nebul1.jpg','common','عادي',1,8,true,'غاز متوهج'),
('Buco Nero Pixel','الثقب الأسود البكسلي','https://i.imgur.com/bucon1.jpg','common','عادي',1,8,true,'جاذبية رقمية'),
('Satellite Glitch','القمر الصناعي المختل','https://i.imgur.com/satell1.jpg','common','عادي',1,8,true,'إشارة مكسورة'),
('Razzo Vapore','الصاروخ البخاري','https://i.imgur.com/razzo1.jpg','common','عادي',1,8,true,'دخان فضاء'),
('Astronauta Fuoco','رائد الفضاء الناري','https://i.imgur.com/astro1.jpg','common','عادي',1,8,true,'بدلة لهب'),
('Alieno Pixel','المخلوق البكسلي','https://i.imgur.com/alien1.jpg','common','عادي',1,8,true,'عيون خضراء'),
('Robot Disco','الروبوت الراقص','https://i.imgur.com/robot1.jpg','common','عادي',1,8,true,'محركات موسيقية'),
('Cyborg Atomico','السايبورغ الذري','https://i.imgur.com/cybor1.jpg','common','عادي',1,8,true,'عضو ميكانيكي'),
('AI Vapore','الذكاء البخاري','https://i.imgur.com/ai001.jpg','common','عادي',1,8,true,'غيمة بيانات'),
('Virus Fuoco','الفيروس الناري','https://i.imgur.com/virus1.jpg','common','عادي',1,8,true,'عدوى ساخنة'),
('Firewall Pixel','جدار النار البكسلي','https://i.imgur.com/firew1.jpg','common','عادي',1,8,true,'حماية رقمية'),
('Server Glitch','الخادم المختل','https://i.imgur.com/serve1.jpg','common','عادي',1,8,true,'خطأ 404'),
('Database Disco','قاعدة البيانات الراقصة','https://i.imgur.com/datab1.jpg','common','عادي',1,8,true,'جداول متوهجة'),
('Cloud Atomico','السحابة الذرية','https://i.imgur.com/cloud1.jpg','common','عادي',1,8,true,'مطر بيانات'),
('WiFi Vapore','واي فاي البخار','https://i.imgur.com/wifi1.jpg','common','عادي',1,8,true,'إشارة ضعيفة'),
('Bluetooth Fuoco','بلوتوث النار','https://i.imgur.com/blue1.jpg','common','عادي',1,8,true,'اقتران ساخن'),
('USB Pixel','الفلاشة البكسلية','https://i.imgur.com/usb001.jpg','common','عادي',1,8,true,'ذاكرة 8-bit'),
('Mouse Laser','الفأرة الليزرية','https://i.imgur.com/mouse1.jpg','common','عادي',1,8,true,'نقر سريع'),
('Tastiera Disco','لوحة المفاتيح الراقصة','https://i.imgur.com/tasti1.jpg','common','عادي',1,8,true,'مفاتيح موسيقية'),
('Schermo Atomico','الشاشة الذرية','https://i.imgur.com/schem1.jpg','common','عادي',1,8,true,'بكسلات متفجرة'),
('Telefono Glitch','الهاتف المختل','https://i.imgur.com/telef1.jpg','common','عادي',1,8,true,'مكالمة مكسورة')

on conflict (id) do nothing;

-- Uncommon (tier 2, weight ~3-5 each) ~40 entries
insert into public.brainrot_characters (name,name_ar,image_url,rarity,rarity_ar,tier,weight,is_real,description) values
('Drago Volante','التنين الطائر','https://i.imgur.com/dragv1.jpg','uncommon','غير شائع',2,5,true,'جناحان ناريان'),
('Squalo Cosmico','القرش الكوني','https://i.imgur.com/squac1.jpg','uncommon','غير شائع',2,5,true,'أسنان نجوم'),
('Ninja Atomico','النينجا الذري','https://i.imgur.com/ninja2.jpg','uncommon','غير شائع',2,5,true,'شوريكين انفجار'),
('Phoenix Pixel','العنقاء البكسلية','https://i.imgur.com/phoen2.jpg','uncommon','غير شائع',2,5,true,'بعث رقمي'),
('Titan Vapore','التيتان البخاري','https://i.imgur.com/titan2.jpg','uncommon','غير شائع',2,5,true,'جسد ضبابي'),
('Leviatano Fuoco','اللوياثان الناري','https://i.imgur.com/levi2.jpg','uncommon','غير شائع',2,5,true,'بحر لهب'),
('Kraken Laser','الكراكن الليزري','https://i.imgur.com/krak2.jpg','uncommon','غير شائع',2,5,true,'مجسات ضوء'),
('Minotauro Disco','المينوتور الراقص','https://i.imgur.com/mino2.jpg','uncommon','غير شائع',2,5,true,'قرنان موسيقيان'),
('Cerbero Glitch','كيربيروس المختل','https://i.imgur.com/cerb2.jpg','uncommon','غير شائع',2,5,true,'ثلاث رؤوس مكسورة'),
('Sirena Atomica','الحورية الذرية','https://i.imgur.com/siren2.jpg','uncommon','غير شائع',2,5,true,'غناء انفجاري'),
('Centauro Vapore','قنطور الضباب','https://i.imgur.com/cent2.jpg','uncommon','غير شائع',2,5,true,'حوافر سحاب'),
('Gorgone Fuoco','الغورغون الناري','https://i.imgur.com/gorg2.jpg','uncommon','غير شائع',2,5,true,'عيون لهب'),
('Chimera Laser','الكيميرا الليزرية','https://i.imgur.com/chim2.jpg','uncommon','غير شائع',2,4,true,'جسد ثلاثي الضوء'),
('Idra Pixel','هيدرا البكسل','https://i.imgur.com/idra2.jpg','uncommon','غير شائع',2,4,true,'رقاب رقمية'),
('Sfinge Disco','الأسد الطنان الراقص','https://i.imgur.com/sfin2.jpg','uncommon','غير شائع',2,4,true,'لغز موسيقي'),
('Pegaso Atomico','بيغاسوس الذري','https://i.imgur.com/pegas2.jpg','uncommon','غير شائع',2,4,true,'حوافر انفجار'),
('Grifone Vapore','العنقاء البخارية','https://i.imgur.com/grif2.jpg','uncommon','غير شائع',2,4,true,'منقار ضبابي'),
('Basilisco Fuoco','الأفعى الملكية النارية','https://i.imgur.com/basil2.jpg','uncommon','غير شائع',2,4,true,'نظرات لهب'),
('Manticora Laser','الماتيكور الليزري','https://i.imgur.com/mant2.jpg','uncommon','غير شائع',2,4,true,'ذيل شوك ضوء'),
('Colosso Pixel','العملاق البكسلي','https://i.imgur.com/colo2.jpg','uncommon','غير شائع',2,4,true,'أقدام 16-bit'),
('Jotun Glitch','الجوتن المختل','https://i.imgur.com/jotun2.jpg','uncommon','غير شائع',2,4,true,'جليد مكسور'),
('Valkiria Disco','الفالكيري الراقصة','https://i.imgur.com/valk2.jpg','uncommon','غير شائع',2,4,true,'رمح موسيقي'),
('Ifrit Atomico','العفريت الذري','https://i.imgur.com/ifrit2.jpg','uncommon','غير شائع',2,4,true,'لهب انفجاري'),
('Golem Vapore','غوليم الضباب','https://i.imgur.com/golem2.jpg','uncommon','غير شائع',2,4,true,'طين سحري'),
('Troll Fuoco','الترول الناري','https://i.imgur.com/troll2.jpg','uncommon','غير شائع',2,4,true,'عصا مشتعلة'),
('Orco Laser','الأورك الليزري','https://i.imgur.com/orco2.jpg','uncommon','غير شائع',2,4,true,'فأس ضوء'),
('Lich Pixel','ليتش البكسل','https://i.imgur.com/lich2.jpg','uncommon','غير شائع',2,4,true,'عظام رقمية'),
('Vampiro Glitch','مصاص الدماء المختل','https://i.imgur.com/vamp2.jpg','uncommon','غير شائع',2,4,true,'أسنان مكسورة'),
('Lupo Mannaro Disco','الرجل الذئب الراقص','https://i.imgur.com/lupom2.jpg','uncommon','غير شائع',2,4,true,'عواء موسيقي'),
('Zombie Atomico','الزومبي الذري','https://i.imgur.com/zomb2.jpg','uncommon','غير شائع',2,4,true,'عدوى انفجارية'),
('Scheletro Vapore','هيكل العظم البخاري','https://i.imgur.com/schel2.jpg','uncommon','غير شائع',2,4,true,'عظام ضبابية'),
('Mummia Fuoco','المومياء النارية','https://i.imgur.com/mumm2.jpg','uncommon','غير شائع',2,4,true,'لفائف لهب'),
('Fantasma Laser','الشبح الليزري','https://i.imgur.com/fant2.jpg','uncommon','غير شائع',2,4,true,'وجه شفاف ضوء'),
('Demone Pixel','الشيطان البكسلي','https://i.imgur.com/demon2.jpg','uncommon','غير شائع',2,4,true,'قرون رقمية'),
('Angelo Glitch','الملاك المختل','https://i.imgur.com/angel2.jpg','uncommon','غير شائع',2,4,true,'أجنحة مكسورة'),
('Genio Disco','الجن الراقص','https://i.imgur.com/genio2.jpg','uncommon','غير شائع',2,4,true,'مصباح موسيقي'),
('Fauno Atomico','الفون الذري','https://i.imgur.com/fauno2.jpg','uncommon','غير شائع',2,4,true,'قرون انفجار'),
('Elfo Vapore','الجنّي البخاري','https://i.imgur.com/elfo2.jpg','uncommon','غير شائع',2,4,true,'سهم ضبابي')
on conflict (id) do nothing;

-- Rare (tier 3, weight ~2 each) ~20 entries
insert into public.brainrot_characters (name,name_ar,image_url,rarity,rarity_ar,tier,weight,is_real,description) values
('Behemoth Pixel','بيهايموث البكسل','https://i.imgur.com/behe3.jpg','rare','نادر',3,2,true,'جسد رقمي ضخم'),
('Ziz Cosmico','الزيز الكوني','https://i.imgur.com/ziz3.jpg','rare','نادر',3,2,true,'جناحان يحجبان الشمس'),
('Anzu Atomico','عنزو الذري','https://i.imgur.com/anzu3.jpg','rare','نادر',3,2,true,'نسر الانفجار'),
('Quetzalcoatl Laser','كيتزالكواتل الليزري','https://i.imgur.com/quetz3.jpg','rare','نادر',3,2,true,'أفعى ضوء تحلق'),
('Sleipnir Vapore','سليبنير البخاري','https://i.imgur.com/slei3.jpg','rare','نادر',3,2,true,'ثمانية حوافر سحاب'),
('Fenrir Fuoco','فنرير الناري','https://i.imgur.com/fenr3.jpg','rare','نادر',3,2,true,'ذئب راجناروك'),
('Jormungandr Glitch','يورمونغاندر المختل','https://i.imgur.com/jorm3.jpg','rare','نادر',3,2,true,'أفعى العالم المكسورة'),
('Nidhogg Disco','نيدهوغ الراقص','https://i.imgur.com/nidh3.jpg','rare','نادر',3,2,true,'جذور يلمس الموت'),
('Hel Pixel','هيل البكسل','https://i.imgur.com/hel3.jpg','rare','نادر',3,2,true,'نصف جميل نصف عظم'),
('Surtr Atomico','سورت الذري','https://i.imgur.com/surt3.jpg','rare','نادر',3,2,true,'سيف الشمس'),
('Ymir Vapore','يمير البخاري','https://i.imgur.com/ymir3.jpg','rare','نادر',3,2,true,'عملاق الجليد الأصلي'),
('Baba Yaga Fuoco','بابا ياغا النارية','https://i.imgur.com/baba3.jpg','rare','نادر',3,2,true,'كوخ دجاج مشتعل'),
('Koschei Laser','كوششي الليزري','https://i.imgur.com/kosc3.jpg','rare','نادر',3,2,true,'خالد الضوء'),
('Rakshasa Pixel','الراكشاسا البكسلي','https://i.imgur.com/raks3.jpg','rare','نادر',3,2,true,'شيطان رقمي'),
('Oni Glitch','الأوني المختل','https://i.imgur.com/oni3.jpg','rare','نادر',3,2,true,'تسونومي مكسورة'),
('Tengu Disco','تينغو الراقص','https://i.imgur.com/tengu3.jpg','rare','نادر',3,2,true,'أنف طويل موسيقي'),
('Kirin Atomico','الكيرين الذري','https://i.imgur.com/kirin3.jpg','rare','نادر',3,2,true,'وحيد قرن يمشي على النار'),
('Baku Vapore','باكو البخاري','https://i.imgur.com/baku3.jpg','rare','نادر',3,2,true,'يأكل الكوابيس'),
('Tanuki Fuoco','تانوكي الناري','https://i.imgur.com/tanuk3.jpg','rare','نادر',3,2,true,'خرافات مشتعلة'),
('Kitsune Laser','الكيتسوني الليزرية','https://i.imgur.com/kitsu3.jpg','rare','نادر',3,2,true,'تسع ذيول ضوء')
on conflict (id) do nothing;

-- Epic (tier 4, weight ~1 each) ~10 entries
insert into public.brainrot_characters (name,name_ar,image_url,rarity,rarity_ar,tier,weight,is_real,description) values
('Bahamut Pixel','باهاموت البكسل','https://i.imgur.com/baha4.jpg','epic','ملحمي',4,1,true,'تنين اللانهائي الرقمي'),
('Tiamat Cosmico','تيامات الكونية','https://i.imgur.com/tiam4.jpg','epic','ملحمي',4,1,true,'أم الوحوش النجمية'),
('Leviatano Supremo Atomico','اللوياثان الأعلى الذري','https://i.imgur.com/levis4.jpg','epic','ملحمي',4,1,true,'بحر الانفجار الأبدي'),
('Phoenix Eterno Laser','العنقاء الخالدة الليزرية','https://i.imgur.com/phoe4.jpg','epic','ملحمي',4,1,true,'تجديد ضوء لانهائي'),
('Kraken Omega Vapore','الك راكن أوميغا البخاري','https://i.imgur.com/krak4.jpg','epic','ملحمي',4,1,true,'أعماق المحيط الضبابية'),
('Jormungandr World Serpent Glitch','أفعى العالم المختلة','https://i.imgur.com/jorm4.jpg','epic','ملحمي',4,1,true,'يحيط الكوكب المكسور'),
('Fenrir Devourer Fuoco','مبتلع العالم الناري','https://i.imgur.com/fenr4.jpg','epic','ملحمي',4,1,true,'فك لهب يبتلع القمر'),
('Quetzalcoatl Feathered Serpent Disco','الأفعى المريشة الراقصة','https://i.imgur.com/quet4.jpg','epic','ملحمي',4,1,true,'الحكمة الراقصة'),
('Ziz Sky Titan Pixel','زيز عملاق السماء البكسلي','https://i.imgur.com/ziz4.jpg','epic','ملحمي',4,1,true,'ظل رقمي يحجب الشمس'),
('Anzu Storm Bird Atomico','عنزو طائر العاصفة الذري','https://i.imgur.com/anzu4.jpg','epic','ملحمي',4,1,true,'رياح انفجار لا ترحم')
on conflict (id) do nothing;

-- Legendary (tier 5, weight ~0.5-1 each) ~5 entries
insert into public.brainrot_characters (name,name_ar,image_url,rarity,rarity_ar,tier,weight,is_real,description) values
('Tung Omega','تونغ أوميغا','https://i.imgur.com/tung5.jpg','legendary','أسطوري',5,1,true,'صيحة الفجر الأبدي'),
('Brr Patapim Primordial','بر باتابيم الأولي','https://i.imgur.com/brr5.jpg','legendary','أسطوري',5,1,true,'صوت الخلق نفسه'),
('Bombardiro Crocodilo Supreme','القناص الأعلى','https://i.imgur.com/bomb5.jpg','legendary','أسطوري',5,1,true,'القناص الذي لا يفوت'),
('Glorb the All-Knowing','غلورب العالم بكل شيء','https://i.imgur.com/glorb5.jpg','legendary','أسطوري',5,1,true,'عينان تريان كل شيء'),
('Brainrot Creator','خالق البرينروت','https://i.imgur.com/creat5.jpg','legendary','أسطوري',5,1,true,'المصمم الأصلي')
on conflict (id) do nothing;

-- Secret (tier 6, weight 0 = impossible) ~10 entries
insert into public.brainrot_characters (name,name_ar,image_url,rarity,rarity_ar,tier,weight,is_real,description) values
('Tung Infinity','تونغ اللانهاية','https://i.imgur.com/tung6.jpg','secret','سري',6,0,false,'مستحيل - صدى عبر الأبعاد'),
('Brr Absolute Zero','بر الصفر المطلق','https://i.imgur.com/brr6.jpg','secret','سري',6,0,false,'مستحيل - برودة أبدية'),
('Bombardiro Big Bang','قناص الانفجار العظيم','https://i.imgur.com/bomb6.jpg','secret','سري',6,0,false,'مستحيل - بداية الكون'),
('Glorb Void','غلورب الفراغ','https://i.imgur.com/glorb6.jpg','secret','سري',6,0,false,'مستحيل - ما قبل الوجود'),
('Brainrot Paradox','مفارقة البرينروت','https://i.imgur.com/para6.jpg','secret','سري',6,0,false,'مستحيل - شيء ولا شيء'),
('Tung Observer','تونغ المراقب','https://i.imgur.com/tung6b.jpg','secret','سري',6,0,false,'مستحيل - يراك دائماً'),
('Brr Echo of Time','صدى زمن بر','https://i.imgur.com/brr6b.jpg','secret','سري',6,0,false,'مستحيل - صوت من المستقبل'),
('Bombardiro Last Shot','الطلقة الأخيرة','https://i.imgur.com/bomb6b.jpg','secret','سري',6,0,false,'مستحيل - القناص النهائي'),
('Glorb True Form','الشكل الحقيقي لغلورب','https://i.imgur.com/glorb6b.jpg','secret','سري',6,0,false,'مستحيل - لا يمكن إدراكه'),
('Brainrot Singularity','تفرد البرينروت','https://i.imgur.com/sing6.jpg','secret','سري',6,0,false,'مستحيل - كل شيء ولا شيء')
on conflict (id) do nothing;
